pipeline:
  name: test9
  identifier: test9
  projectIdentifier: Harnessproject1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubaction1
        build: <+input>
  stages:
    - stage:
        name: test9
        identifier: test9
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - image: plugins/github-actions
                name: hello world
                identifier: hello_world
                spec:
                  uses: GitHubAction/example-basic@main
