pipeline:
  name: hello-world.yml
  identifier: helloworldyml
  projectIdentifier: Harnessproject1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubaction1
        build: <+input>
  stages:
    - stage:
        name: hi
        identifier: hi
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sconnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: ubuntu
                    shell: Sh
                    envVariables:
                      Authorize: <+input>
